config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|ar/ do
    get 'errors/not_found'

    get 'errors/unacceptable'

    get 'errors/internal_error'

    get 'addresses/create'

    get 'addresses/show'

    get 'addresses/index'

    get 'addresses/edit'

    get 'addresses/update'

    get 'addresses/destroy'

    get 'sessions/new'

    get 'users/new'

    root 'static_pages#home'
    get '/help', to: 'static_pages#help'
    get '/about', to: 'static_pages#about'
    get '/frames', to: 'static_pages#frames'
    get '/prints', to: 'static_pages#prints'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
    get '/activate', to: 'users#activate'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    resources :users
    resources :addresses
    resources :photos, only: [:create, :destroy, :index]
    resources :password_resets, only: [:new, :edit, :create, :update]
    post 'photos/add_photos'
    get '/upload', to: 'photos#new'
    resources :account_activations, only: [:edit]
    post 'orders/add_to_cart'
    get 'orders/choose_sizes'
    get 'orders/backend_dashboard', as: 'backend_dashboard'
    get 'orders/backend_dashboard/:id', to: 'orders#backend_order', as: 'backend_order'
    get 'confirm', to: 'orders#confirm'
    get 'success', to: 'orders#successful_order'
    get 'shipping', to: 'orders#choose_address'
    get 'checkout_guest', to: 'orders#checkout_guest'
    get 'send_printing_email', to: 'orders#send_printing_email'
    patch 'set_address', to: 'orders#set_address'
    patch 'place_order', to: 'orders#place_order'
    patch 'checkout', to: 'orders#checkout'
    patch 'remove_item', to: 'orders#remove_item'
    patch 'update_quantity', to: 'orders#update_quantity'
    patch 'change_status', to: 'orders#change_status'
    patch 'set_guest_email', to: 'orders#set_email'
    get '/cart', to: 'orders#cart'

    mount UPPY_S3_MULTIPART_APP => "/s3/multipart"

    # Errors
    get "/404", :to => "errors#not_found"
    get "/422", :to => "errors#unacceptable"
    get "/500", :to => "errors#internal_error"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: reset_params[:email])
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Reset password has been sent to your email"
      redirect_to root_url
    else
      flash[:danger] = "Email does not exist"
      render 'new'
    end
  end

  def edit
  end

  def update
    if user_params[:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      login @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reset successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def reset_params
    params.require(:password_reset).permit(:email)
  end

  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has expired"
      redirect_to new_password_reset_url
    end
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end


  def get_user
    @user = User.find_by(email: params[:email])
  end

  def valid_user
    unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
      redirect_to root_url
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error-messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Reset Password") %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel-heading"><h3><%= t("password_reset.title") %></h3></div>
		<div class="panel-body">
			<%= form_for(:password_reset, url:password_resets_path) do |f| %>
			<%= f.label :email, t("activerecord.attributes.user.email") %>
      		<%= f.email_field :email, class: 'form-control' %>

      		<%= f.submit t("password_reset.button"), class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>