config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|ar/ do
    get 'errors/not_found'

    get 'errors/unacceptable'

    get 'errors/internal_error'

    get 'addresses/create'

    get 'addresses/show'

    get 'addresses/index'

    get 'addresses/edit'

    get 'addresses/update'

    get 'addresses/destroy'

    get 'sessions/new'

    get 'users/new'

    root 'static_pages#home'
    get '/help', to: 'static_pages#help'
    get '/about', to: 'static_pages#about'
    get '/frames', to: 'static_pages#frames'
    get '/prints', to: 'static_pages#prints'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
    get '/activate', to: 'users#activate'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    resources :users
    resources :addresses
    resources :photos, only: [:create, :destroy, :index]
    resources :password_resets, only: [:new, :edit, :create, :update]
    post 'photos/add_photos'
    get '/upload', to: 'photos#new'
    resources :account_activations, only: [:edit]
    post 'orders/add_to_cart'
    get 'orders/choose_sizes'
    get 'orders/backend_dashboard', as: 'backend_dashboard'
    get 'orders/backend_dashboard/:id', to: 'orders#backend_order', as: 'backend_order'
    get 'confirm', to: 'orders#confirm'
    get 'success', to: 'orders#successful_order'
    get 'shipping', to: 'orders#choose_address'
    get 'checkout_guest', to: 'orders#checkout_guest'
    get 'send_printing_email', to: 'orders#send_printing_email'
    patch 'set_address', to: 'orders#set_address'
    patch 'place_order', to: 'orders#place_order'
    patch 'checkout', to: 'orders#checkout'
    patch 'remove_item', to: 'orders#remove_item'
    patch 'update_quantity', to: 'orders#update_quantity'
    patch 'change_status', to: 'orders#change_status'
    patch 'set_guest_email', to: 'orders#set_email'
    get '/cart', to: 'orders#cart'

    mount UPPY_S3_MULTIPART_APP => "/s3/multipart"

    # Errors
    get "/404", :to => "errors#not_found"
    get "/422", :to => "errors#unacceptable"
    get "/500", :to => "errors#internal_error"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/order.rb
# frozen_string_literal: true

STATUS_VALUES = { 0 => 'CART', 1 => 'ORDERED', 2 => 'CONFIRMED', 3 => 'DELIVERED', 4 => 'CANCELED' }.freeze
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address, optional: true
  has_many :order_items, inverse_of: :order
  has_many :photos, through: :order_items
  has_many :photo_sizes, through: :order_items
  accepts_nested_attributes_for :order_items
  before_save :status_changed_to_ordered

  def total
    total = 0
    order_items.each do |item|
      total += item.quantity * item.selling_price
    end
    total
  end

  def status_word
    STATUS_VALUES[status]
  end

  def send_printing_email
    OrderMailer.printer_photos(self).deliver_now
  end

  # private

  def secure_order_token
    DateTime.now.strftime('%Y%m%d').to_s + '-' + rand(9999).to_s
  end

  def generate_order_number
    order_number = nil
    loop do
      order_number = secure_order_token
      break unless Order.exists?(order_number: order_number)
    end

    self.order_number = order_number
  end

  def status_changed_to_ordered
    return unless status_changed? && status == 1

    self.ordered_at = Time.now
    generate_order_number
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :logged_in_user, except: [:cart]
  before_action :create_guest_if_needed, only: [:cart]
  before_action :cart_is_not_empty, only: %i[checkout confirm choose_address]
  before_action :admin_user, only: %i[backend_dashboard backend_order]
  before_action :fetch_cart, only: %i[update_quantity remove_item checkout
                                      set_address confirm place_order]
  before_action :fetch_current_user, only: %i[add_to_cart choose_sizes cart
                                              set_email checkout_guest choose_address]

  def add_to_cart
    @cart = @user.cart || @user.build_cart

    @cart.attributes = add_to_cart_params

    @cart.order_items.reject(&:persisted?).each do |order_item|
      if order_item.frame_id
        order_item.frame_size_id = order_item.item_size_id
        order_item.selling_price = order_item.frame_size.selling_price
      else
        order_item.photo_size_id = order_item.item_size_id
        order_item.selling_price = order_item.photo_size.selling_price
      end
    end
    if @cart.save
      redirect_to cart_url
    else
      abort(@cart.errors.inspect)
    end
  end

  def choose_sizes
    if session[:uploaded_photos_ids]
      @order = @user.orders.build
      @frames = Frame.all
      uploaded_photos_ids = session[:uploaded_photos_ids]
      @uploaded_photos = Photo.find uploaded_photos_ids
      session.delete(:uploaded_photos_ids)
      render '/orders/choose_photo_sizes'
    else
      flash[:danger] = 'You need to upload photos before choosing sizes'
      redirect_to upload_path

      # Comment from else till here, and uncomment whats below if you want to test the
      # choose_photo_sizes page correctly

      # @user = current_user
      # @order = @user.orders.build
      # @frames = Frame.all
      # uploaded_photos_ids = session[:uploaded_photos_ids]
      # @uploaded_photos = Photo.find([796,795,794])
      # session.delete(:uploaded_photos_ids)
      # render '/orders/choose_photo_sizes'
    end
  end

  def cart
    @cart = @user.cart
  end

  def update_quantity
    order_item_id = update_quantity_params[:order_item_id]
    sent_order_item = update_quantity_params[:cart][:order_items_attributes].to_hash.values[0]

    quantity = sent_order_item['quantity']
    @cart_item = OrderItem.find(order_item_id)
    @cart_item.quantity = quantity
    @cart_item.save
    if @cart.order_items.where('quantity > 0').any?
      respond_to do |format|
        format.html { redirect_to cart_path }
        format.js
      end
    else
      redirect_to cart_path
    end
  end

  def remove_item
    cart_item = OrderItem.find(remove_item_params[:order_item_id])
    cart_item.quantity = 0
    cart_item.save
    if @cart.order_items.where('quantity > 0').any?
      respond_to do |format|
        format.html { redirect_to cart_path }
        format.js
      end
    else
      redirect_to cart_path
    end
  end

  def checkout
    @cart.update_attributes(checkout_params)

    abort(@cart.errors.inspect) unless @cart.save

    if current_user.guest?
      redirect_to checkout_guest_path
    elsif current_user.addresses.any?
      redirect_to shipping_path
    else
      redirect_to new_address_path
    end
  end

  def checkout_guest; end

  def set_email
    @user.email = params.require(:user).permit(:email)[:email]
    @user.save
    redirect_to new_address_path
  end

  def choose_address
    @order = current_user.cart
    @addresses = current_user.addresses
    if @addresses
      render 'choose_address'
    else
      @address = current_user.addresses.build
      render 'addresses/new'
    end
  end

  def set_address
    return unless @cart

    @cart.address_id = set_address_params[:address_id]
    @cart.save
    redirect_to confirm_path
  end

  def confirm
    render 'confirm'
  end

  def place_order
    return unless @cart.place_order

    current_user.send_confirm_order_email(@cart)
    redirect_to success_path
  end

  def successful_order
    @order = current_user.orders.last
    render 'success'
  end

  def change_status
    @order = Order.find(change_status_params[:order_id])
    @order.status = change_status_params[:status]

    respond_to do |format|
      if @order.save
        format.html { redirect_to backend_dashboard_path, notice: 'Status has been changed' }
        format.js
      else
        format.html { redirect_to backend_dash_path, notice: 'An error occured. Status was not changed' }
      end
    end
  end

  def send_printing_email
    order_id = send_printing_email_params[:order_id]
    order = Order.find(order_id)
    order.send_printing_email
    flash[:success] = 'Mail has been sent'
    redirect_to backend_dashboard_path
  end

  def backend_dashboard
    @orders = if filter_dashboard_params[:status]
                Order.where(status: filter_dashboard_params[:status])
              else
                Order.where.not(status: 0)
              end
  end

  def backend_order
    @order = Order.find(params[:id])
  end

  def add_to_cart_params
    params.require(:order).permit(order_items_attributes: %i[item_size_id frame_id photo_id quantity])
  end

  def checkout_params
    params.require(:cart).permit(order_items_attributes: %i[id quantity])
  end

  def update_quantity_params
    params.permit({ cart: { order_items_attributes: %i[id quantity] } }, :order_item_id)
  end

  def set_address_params
    params.require(:cart).permit(:address_id)
  end

  def change_status_params
    params.require(:order).permit(:order_id, :status)
  end

  def remove_item_params
    params.permit(:order_item_id)
  end

  def send_printing_email_params
    params.permit(:order_id)
  end

  def filter_dashboard_params
    params.permit(status: [])
  end

  private

  def fetch_cart
    @cart = current_user.cart
  end

  def fetch_current_user
    @user = current_user
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def frame_css_class(frame)
    if !frame
      nil
    elsif frame.name == 'Bold'
      'bold_frame'
    elsif frame.name == 'Classic'
      'classic_frame'
    elsif frame.name == 'Clean'
      'clean_frame'
    else frame.name == 'Ever'
      'ever_frame'
    end
  end

  def photo_without_frames_grouped_options
    unframed_photo_sizes = PhotoSize.all.select('size, selling_price, id').where(:is_frame => [false, nil]).order(:selling_price)
    photos_without_frames_sizes = []
    unframed_photo_sizes.each do |photo_size|
      photos_without_frames_sizes.push([photo_size.size_and_price, photo_size.id])
    end
    grouped_options = {'Photo without frame' => photos_without_frames_sizes}
  end

  def non_matted_framed_photo_grouped_options
    framed_photo_sizes = FrameSize.all.where(:is_matted => false).order(:selling_price)
    frame_with_photo_sizes = []
    framed_photo_sizes.each do |framed_size|
      frame_with_photo_sizes.push([framed_size.size_and_price, framed_size.id])
    end
    grouped_options = {
      'Frame with photo' => frame_with_photo_sizes
    }
  end

  def matted_framed_photos_grouped_options
    framed_photo_sizes = FrameSize.all.where(:is_matted => true).order(:selling_price)
    frame_with_photo_sizes = []
    framed_photo_sizes.each do |framed_size|
      frame_with_photo_sizes.push([framed_size.size_and_price, framed_size.id])
    end
    grouped_options = {
      'Frame with photo' => frame_with_photo_sizes
    }
  end

end

app/views/orders/_cart-form.html.erb
<%= form_for @cart, url: checkout_path do |order_form| %>
     <div class="col-lg-8 col-md-12 col-sm-12">
          <div id="cart_items">
               <%= order_form.fields_for :order_items, @cart.order_items.where("quantity > 0") do |order_item| %>
                    <%= render 'cart_row', order_item_form: order_item %>
               <% end %>
          </div>
     </div>
     <div class="clearfix hidden-lg"></div>
     <div class="col-lg-4 col-md-12 col-sm-12 box-div">
          <%= render 'orders/boxes/checkout-box', cart: @cart, order_form: order_form %>
     </div>
<% end %>

app/views/orders/_cart_row.html.erb
<% order_item = order_item_form.object %>
<div class="photo-row row">
	<div class="col-md-7 col-sm-7 col-xs-7">
		<%= order_item_form.hidden_field :id %>
		<% frame_class = frame_css_class(order_item.frame) %>
		<% if order_item.photo.thumbnail_path.present? %>
      		<%= image_tag(order_item.photo.thumbnail_path, :class => "#{frame_class} cart_photo") %>
        	<% else %>
      		<%= image_tag(order_item.photo.path, {class: "#{frame_class} framed_photo_original cart_photo"}) %>
        	<% end %>
	</div>
	<div class="form-group col-md-3 col-sm-3 col-xs-3">
		<% if order_item.frame %>
			<% frame_size = order_item.frame_size ? order_item.frame_size.size : order_item.photo_size.size %>
			<p> <%= t("cart_page.frame_description", frame_size: order_item.frame_size.size) %> </p>
		<% else %>
			<p><%= t("cart_page.printing_description", photo_size: order_item.photo_size.size) %></p>
		<% end %>
		<%= order_item_form.number_field :quantity, class: "form-control", min: 0, data: { remote: true, method: :patch, url: update_quantity_path(order_item_id: order_item.id) } %>
		<%= link_to t('cart_page.remove'), remove_item_path(:order_item_id => order_item.id), remote: true, method: :patch, class: "remove_fields" %>
	</div>
	<div class="form-group col-md-2 col-sm-2 col-xs-2 my-color text-right currency" <%=  "id=total_for_#{order_item.id}" %>>
		<%= order_item.selling_price * order_item.quantity %> <%= t("currencies.egp") %>
	</div>
</div>


<script>
$(function () {
	$('a.remove_fields').click( function() {
		$(this).prev('input[type=number]').val('0');
		$(this).closest('div.photo-row').hide();
	});
});
</script>

app/views/orders/_order.html.erb
<tr>
     <td> <%= link_to order.id, backend_order_path(order) %> </td>
     <td> <%= order.user.present? ? order.user.name : " " %> </td>
     <td> <%= order.address.present? ? order.address.mobile_no : " "%> </td>
     <td> <%= order.address.present? ? order.address.text_address : " No address"%> </td>
     <td> <%= order.ordered_at ? order.ordered_at.in_time_zone('Cairo') : "updated not ordered " + order.updated_at.in_time_zone('Cairo').to_s %> </td>
     <td> <%= order.total %> </td>
     <td id='<%= "status_for_order_#{order.id}" %>'> <%= order.status_word %> </td>
     <td>
          <% if order.status < 2 %>
               <%= form_with(model: order, url: change_status_path, local: false) do |order_form| %>
                    <%= order_form.hidden_field :order_id, value:order.id  %>
                    <%= order_form.hidden_field :status, value:2 %>
                    <%= order_form.submit "Mark as confirmed", class: "btn btn-success" %>
               <% end %>
          <% end %>
          <% if order.status < 3 %>
               <%= form_with(model: order, url: change_status_path, local: false) do |order_form| %>
                    <%= order_form.hidden_field :order_id, value:order.id  %>
                    <%= order_form.hidden_field :status, value: 3 %>
                    <%= order_form.submit "Mark as deliverd", class: "btn btn-primary" %>
               <% end %>
          <% end %>
          <% if order.status < 4 %>
               <%= form_with(model: order, url: change_status_path, local: false) do |order_form| %>
                    <%= order_form.hidden_field :order_id, value:order.id  %>
                    <%= order_form.hidden_field :status, value: 4 %>
                    <%= order_form.submit "Mark as canceled", class: "btn btn-danger" %>
               <% end %>
          <% end %>

          <%= link_to 'Send Printing mail', send_printing_email_path(:order_id => order.id) %>
     </td>
</tr>

app/views/orders/_size_guide_modal.html.erb
<%

frame_1 = { :name => "13x18", :photo => "13x15_example.jpg"};
frame_2 = { :name => "15x21", :photo => "15x18_example.jpg"};
frame_3 = { :name => "20x25", :photo => "20x30_example.jpg"};

examples_array = [frame_1,frame_2,frame_3];

%>

<div id="sizeGuide" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content size-guide-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Prints and frames sizes</h4>
      </div>
      <div class="modal-body">
        <div class="scrolling-wrapper">



        <% examples_array.each do |frame_example|%>
          <div class="photo-example">
              <%= image_tag(frame_example[:photo])  %>
              <div class="description">
				        <%= frame_example[:name] %>
			        </div>
          </div>
        <% end %>


        </div>
      </div>
    </div>

  </div>
</div>

app/views/orders/backend_dashboard.html.erb
<% provide(:title, "Dashboard") %>

<% if @orders.any? %>
<h3>Orders (<%= @orders.count %>)</h3>

     <%= form_for backend_dashboard_path, method: :get do |filter_form| %>
          <%= filter_form.label :status do %>
               <%= check_box_tag("status[]", 1) %>Ordered
          <% end %>
          <%= filter_form.label :status do %>
               <%= check_box_tag("status[]", 2) %>Confirmed
          <% end %>
          <%= filter_form.label :status do %>
               <%= check_box_tag("status[]", 3) %>Delivered
          <% end %>
          <%= filter_form.label :status do %>
               <%= check_box_tag("status[]", 4) %>Canceled
          <% end %>

          <%= filter_form.submit "Filter", class: "btn btn-primary" %>
     <% end %>
     <table class="dashboard-orders">
          <tr>
               <th>Order Id</th>
               <th>Customer name</th>
               <th>Phone no.</th>
               <th>Address</th>
               <th>Ordered at</th>
               <th>Total before shipping</th>
               <th>Status</th>
               <th>Take action</th>
          </tr>
          <%= render @orders.order(created_at: :desc) %>
     </table>
<% end %>

app/views/orders/change_status.js.erb
$('<%= "#status_for_order_#{@order.id}" %>').html('<%= @order.status_word %>');

app/views/orders/checkout_guest.html.erb
<% provide(:title, "Checkout") %>


<div class="checkout-guest-page container">
  <h3>Checkout</h3>
  <p>Select your preferred checkout method</p>
  <div class="row box-div">

    <div class="col-lg-6 col-md-6 col-md-push-6 col-sm-12">
      <%= render 'orders/boxes/checkout-guest' %>
    </div>

    <div class="col-lg-6 col-md-6 col-md-pull-6 col-sm-12">
      <%= render 'orders/boxes/guest-login' %>
    </div>

  </div>
</div>

app/views/orders/choose_address.html.erb
<% provide(:title, "Choose Address") %>

<div class="container">


  <div class="row choose-address-upper-bar">
    <h3><%= t("choose_address.shipping_address") %></h3>
  </div>

  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-9 choose-address-upper-bar">
    </div>
    <div class="col-md-3 create-new-address-button">
      <%= button_to t("choose_address.create_new_address"), new_address_path, method: :get, class: "btn create-address" %>
    </div>
  </div>



  <%= form_for @order, url: set_address_path do |order_form| %>
    <div class="row">
        <% if @addresses.any? %>
          <% @addresses.each do |address| %>
            <%= order_form.hidden_field :address_id, value: address.id %>
            <div class="col-sm-10 col-md-4" id="choose_address_box">
              <div class="box">
                <%= address.name ? simple_format(address.name) : simple_format(address.user.name) %>
                <%= simple_format(address.text_address) %>
                <%= t("activerecord.attributes.address.mobile_no") + ": "+ address.mobile_no %>
                <%= order_form.submit t("choose_address.choose_this"), class: "btn btn-primary" %>
              </div>
            </div>
            <% end %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/orders/choose_photo_sizes.html.erb
<% provide(:title, "Choose sizes") %>
<%= form_for @order, url: orders_add_to_cart_path do |order_form| %>
  <% if @uploaded_photos.any? %>
  <div class="container">
    <h3><%= t("choose_sizes.choose_sizes_title", number_of_photos: @uploaded_photos.count )  %></h3>
    <div class="row">
      <div class="col-sm-12 col-md-10 row choose-sizes-table">
        <% @uploaded_photos.each do |photo| %>
            <%= render 'choose_photo_size', photo: photo, f: order_form, order: @order %>
          <% end %>
      <% end %>
      </div>
    </div>
    <div id="add-to-cart-wrapper" class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
      <%= order_form.submit t("buttons.add_to_cart"), class: "btn btn-primary col-md-5" %>
      <% end %>
    </div>
  </div>

app/views/orders/remove_item.js.erb
$(".total_price").html('<%= @cart.total %> EGP');

app/views/orders/success.ar.html.erb
<% provide(:title, "Success") %>
<%= render 'shared/conversion-tag'%>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <div class="text-center">
          <%= image_tag("correct_icon.png", :class => "correct_icon")  %>
          <h2><%= @order.user.name %>, شكراً على طلبك!</h2>

          <div style="font-size: 16px; margin-top: 30px;"><p>تم إرسال ايميل تأكيد على عنوان  <%= @order.user.email %> <br/>
          رقم الطلب:  <%= @order.order_number %></div>

          <div style="font-size:16px; margin-top: 15px;"><p><span style="font-weight: bold">واجهك مشكلة أو عندك سؤال أو إقتراح؟ </span>كلمنا في أي وقت على <a>01004100209</a></p></div>
        </div>

  </div>
</div>

app/views/orders/success.en.html.erb
<% provide(:title, "Success") %>
<%= render 'shared/conversion-tag'%>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <div class="text-center">
          <%= image_tag("correct_icon.png", :class => "correct_icon")  %>
          <h3><%= @order.user.name + "," if @order.user.name?%> Thanks for your order!</h3>

          <div style="margin-top: 30px;"><p>A confirmation email has been sent to <%= @order.user.email %> <br/>
          Order no.#<%= @order.order_number %></div>

          <div style="margin-top: 15px;"><p><span style="font-weight: bold">Faced problems, or have a question or suggestion?</span> Call or text us now on <a>+201004100209</a></p></div>
        </div>

  </div>
</div>

app/views/orders/update_quantity.js.erb
$("#total_for_<%= @cart_item.id%>").html('<%= "#{@cart_item.selling_price * @cart_item.quantity} EGP"%>');
$(".total_price").html('<%= @cart.total %> EGP');