config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|ar/ do
    get 'errors/not_found'

    get 'errors/unacceptable'

    get 'errors/internal_error'

    get 'addresses/create'

    get 'addresses/show'

    get 'addresses/index'

    get 'addresses/edit'

    get 'addresses/update'

    get 'addresses/destroy'

    get 'sessions/new'

    get 'users/new'

    root 'static_pages#home'
    get '/help', to: 'static_pages#help'
    get '/about', to: 'static_pages#about'
    get '/frames', to: 'static_pages#frames'
    get '/prints', to: 'static_pages#prints'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
    get '/activate', to: 'users#activate'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    resources :users
    resources :addresses
    resources :photos, only: [:create, :destroy, :index]
    resources :password_resets, only: [:new, :edit, :create, :update]
    post 'photos/add_photos'
    get '/upload', to: 'photos#new'
    resources :account_activations, only: [:edit]
    post 'orders/add_to_cart'
    get 'orders/choose_sizes'
    get 'orders/backend_dashboard', as: 'backend_dashboard'
    get 'orders/backend_dashboard/:id', to: 'orders#backend_order', as: 'backend_order'
    get 'confirm', to: 'orders#confirm'
    get 'success', to: 'orders#successful_order'
    get 'shipping', to: 'orders#choose_address'
    get 'checkout_guest', to: 'orders#checkout_guest'
    get 'send_printing_email', to: 'orders#send_printing_email'
    patch 'set_address', to: 'orders#set_address'
    patch 'place_order', to: 'orders#place_order'
    patch 'checkout', to: 'orders#checkout'
    patch 'remove_item', to: 'orders#remove_item'
    patch 'update_quantity', to: 'orders#update_quantity'
    patch 'change_status', to: 'orders#change_status'
    patch 'set_guest_email', to: 'orders#set_email'
    get '/cart', to: 'orders#cart'

    mount UPPY_S3_MULTIPART_APP => "/s3/multipart"

    # Errors
    get "/404", :to => "errors#not_found"
    get "/422", :to => "errors#unacceptable"
    get "/500", :to => "errors#internal_error"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer font-small blue pt-4">

  <!-- Footer Links -->
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
    <div><%= t('footer.have_questions')%></div>
    <span style="font-weight: 700;"><%= t('footer.call_us')%></span>
    <div id="copyright" style="padding-top: 10px">©2021 printpicsnow.com</div>
  </div>
  <!-- Copyright -->

</footer>

app/views/layouts/_header.ar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header pull-right">
      <%= link_to "Printpicsnow!".html_safe, root_path,  class: "navbar-brand", id: "logo" %>
    </div>
      <ul class="nav navbar-nav navbar-left pull-left">


        <% if logged_in? %>

          <li class="dropdown horizontal-item">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <%= current_user.name + " " %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("header.account_settings_link"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("header.log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>

        <li class="horizontal-item"><%= link_to "", cart_path, { :class => "glyphicon glyphicon-shopping-cart"} %></li>
        <% else %>
          <li class="horizontal-item"><%= link_to t('header.log_in'), login_path %></li>
          <li class="horizontal-item"><%= link_to t('header.register'), signup_path %></li>
          <% if I18n.locale == :en %>
               <li class="horizontal-item"><%= link_to 'عربي', root_path(locale: :ar) %></li>
          <% else %>
               <li class="horizontal-item"><%= link_to 'English', root_path(locale: :en) %></li>
          <% end %>
        <% end %>
      </ul>
  </div>
</header>

app/views/layouts/_header.en.html.erb
<header class="navbar navbar-fixed-top navbar-inverse hidden-xs">
  <div class="container">
      <ul class="nav navbar-nav navbar-right pull-right">
        <% if current_user && !current_user.guest? %>
            <li class="dropdown horizontal-item">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name + " " %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("header.account_settings_link"), edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t("header.log_out"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>

            <li class="horizontal-item"><%= link_to "", cart_path, { :class => "glyphicon glyphicon-shopping-cart"} %></li>
      <% else %>
            <li class="horizontal-item"><%= link_to t('header.log_in'), login_path %></li>
            <li class="horizontal-item"><%= link_to t('header.register'), signup_path %></li>
            <li class="horizontal-item"><%= link_to "", cart_path, { :class => "glyphicon glyphicon-shopping-cart"} %></li>
      <% end %>
      </ul>
  </div>
</header>



<header class="navbar navbar-fixed-top navbar-inverse visible-xs">
</header>


<nav class="navbar navbar-lower navbar-default hidden-xs">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to(root_path, :class=> "navbar-brand" ) do %>
         <%= image_tag("new-logo.svg")  %>
      <% end %>
    </div>
  </div>
</nav>


<nav class="navbar navbar-lower navbar-default visible-xs">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(root_path, :class=> "navbar-brand" ) do %>
         <%= image_tag("new-logo.svg")  %>
      <% end %>

      <%= link_to "", cart_path, { :class => "glyphicon glyphicon-shopping-cart"} %>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <% if current_user && !current_user.guest? %>
            <li><%= link_to t("header.account_settings_link"), edit_user_path(current_user) %></li>
            <li><%= link_to t("header.log_out"), logout_path, method: :delete %></li>
        <% else %>
            <li><%= link_to t('header.log_in'), login_path %></li>
            <li><%= link_to t('header.register'), signup_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/_lang.html.erb
<% if I18n.locale == :en %>
     <li><%= link_to 'عربي', root_path(locale: :ar) %></li>
<% else %>
     <li><%= link_to 'English', root_path(locale: :en) %></li>
<% end %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if Rails.env.production? %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139472338-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-139472338-1');
          gtag('config', 'AW-434702771');
      </script>
    <% end %>
    <%= yield :head %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body class="<%= I18n.locale %>">
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>